# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

horror = Genre.create(name: 'Horror')
drama = Genre.create(name: 'Drama')
romcom = Genre.create(name: 'Romantic Comedy')
action = Genre.create(name: 'Action')
scifi = Genre.create(name: 'Science Fiction')
crime = Genre.create(name: 'Crime')
adventure = Genre.create(name: 'Adventure')
thriller = Genre.create(name: 'Thriller')
sports = Genre.create(name: 'Sports')
fantasy = Genre.create(name: 'Fantasy')
western = Genre.create(name: 'Western')

troll = Movie.create(genre_id: 1, title: "Troll 2", description: "Michael Waits has always dreamed of being a farmer, and arranges a home exchange vacation in which he and his family will move into a house in the rural farming community of Nilbog ('goblin' spelled backwards) for a month. The night before the family is scheduled to leave, Michael's son Joshua is contacted by the ghost of his dead grandfather, Seth, warning him that vegetarian goblins want to mutate him and his family into plants so that they can eat them. Seth tells Joshua that goblins can mutate people into plants by feeding them poisoned food or drink.

Meanwhile, Joshua's sister, Holly, receives a visit from her boyfriend Elliot Cooper. Holly accuses Elliot of being a homosexual since he seems to prefer spending time with his friends. Elliot promises to show his devotion by accompanying the family on vacation.

The next morning, Elliot fails to arrive and the family leaves without him; they encounter him en route to Nilbog, riding in an RV with his friends Arnold, Drew, and Brent. Outside of Nilbog, Seth appears as a hitchhiker, who warns Joshua that Nilbog is the kingdom of the goblins, and that if his family eats anything while they are there, they will be mutated into plants. The family disbelieves Joshua's warnings and continue on to Nilbog, where they meet their strange and aloof exchange family, the Presents. There, Joshua sets about destroying all of the food the family finds or acquires, such as by urinating over a feast prepared for them, with the help of Seth's ghost.

Arnold goes for a walk outside of Nilbog and encounters a girl being chased by goblins. When Arnold approaches them and insults them, they respond by throwing a spear into his chest. They flee to a chapel in the woods, where they encounter the goblins' queen, Druid Witch Creedence Leonore Gielgud, who uses the 'Stonehenge Magic Stone' to give the goblins power. Creedence tricks them into drinking a magic potion that dissolves the girl into vegetable matter, a horrifying scene witnessed by Arnold which prompt him to scream helplessly only to be mutated into a tree.

The following morning, Michael and Joshua venture into town to buy some food, as there is none in their holiday home. When in town, they find the general store closed, and Michael falls asleep on a bench. Joshua enters the local Church and eavesdrops on a goblin church sermon, which bewails the 'evils' of eating meat. The parishioners capture him after seeing his skateboard roll into the church and attempt to force feed him poisonous ice cream; Michael walks in on the scene and becomes suspicious, taking Joshua home.

Later, Drew goes to the town because there are no food or drinks in the RV. The sheriff Gene Freak takes him in his car and gives him a green hamburger. When he arrives in the town, Drew goes to the store and the owner offers him poisonous Nilbog milk. Feeling dizzy, he goes to a chapel and finds Arnold, who has mutated into a tree. Drew drags him out, but Creedence appears. She knocks him out and chainsaws Arnold into pieces. Drew is then killed off-screen.

At the house, the family discover that the townspeople have prepared them a surprise party to apologize for the events at the church. Joshua attempts to make contact with Seth, only for Creedence to appear in goblin form through the mirror, and attacks Joshua. Seth's ghost appears and chops her hand off with an axe. Creedence returns to her chapel, where she mutates herself into a beautiful woman in revealing clothes; she then travels to Elliot's RV, where she seduces Brent and drowns him in popcorn.

During the party, Seth and Joshua try to cause a distraction using a Molotov cocktail, however the Priest captures them, takes the cocktail, and recites a spell which banishes Seth's soul to Hell. However, before he vanishes, Seth summons a bolt of lightning from the sky, which ignites the cocktail and kills the Priest in a fiery explosion. When Michael extinguishes his burning corpse, his true Goblin form is revealed, and the villagers turn on the Waits, revealing themselves all as Goblins. The Waits and Elliot then retreat to the house, where the villagers surround them and hold them hostage.

Joshua, Elliot, Holly, Michael and Diana hold a séance to communicate with Seth, who returns from the dead and tells them that he can retain a physical form for exactly ten minutes before he has to return to the afterlife. Seth gives Joshua a paper bag containing a 'secret weapon' to use against the goblins. The goblins break into the house and transport Joshua to Creedence's chapel, where Joshua opens the bag, revealing a 'double-decker Bologna sandwich'. He eats the sandwich, making his body poisonous to the goblins; he then touches the Stonehenge Stone, along with his family and Elliot, which destroys Creedence and all of the Goblins present.

The family returns home, where Joshua's mother is seen eating food from the refrigerator. The food, unknown to the family, has been poisoned by the family of goblins who took over their home during their exchange in the country. The film ends with Joshua walking in on a group of goblins eating his mother's green, bloated torso off of the kitchen counter and offering him a bite. Joshua screams in horror.

", rating: 3)
the_room = Movie.create(genre_id: 2, title: 'The Room', description: "Johnny is a successful banker who lives in a San Francisco townhouse with his fiancée Lisa, who has become dissatisfied with their relationship. She seduces his best friend, Mark, and the two begin a secret affair. Meanwhile, Johnny, having overheard Lisa confess her infidelity to her mother, Claudette, attaches a tape recorder to their phone in an attempt to identify her lover.

Denny, a neighboring college student Johnny financially and emotionally supports, has a run-in with an armed drug dealer, Chris-R, but Johnny and Mark overpower and detain him. Denny also lusts after Lisa, and confesses this to Johnny, who understands and encourages him to instead pursue one of his classmates. Johnny spirals into a mental haze and calls upon Peter – his and Mark's friend and a psychologist – for help. Mark also confides in Peter that he feels guilty about his affair. When Peter asks Mark if the affair is with Lisa, Mark attacks Peter and attempts to kill him, but they quickly reconcile.

At a surprise birthday party for Johnny, his friend Steven catches Lisa kissing Mark while the other guests are outside and confronts them about the affair. Johnny announces that he and Lisa are expecting a child, although Lisa later reveals she lied about it in order to cover up the truth about the affair. At the end of the evening, Lisa flaunts her affair in front of Johnny, who physically and verbally attacks Mark.

After the party, Johnny locks himself in the bathroom in despair. When he leaves, he retrieves the cassette recorder that he attached to the phone and listens to an intimate call between Lisa and Mark. Outraged, Johnny berates Lisa for betraying him, prompting her to end their relationship permanently and live with Mark. Johnny then has an emotional breakdown, angrily destroying his apartment and committing suicide by shooting himself in the mouth.

Hearing the commotion, Denny, Mark, and Lisa rush up the stairs to find his dead body. Mark blames Lisa for Johnny's death, admonishes her for her deceitful behavior, and tells her to get out of his life. Denny tells Lisa and Mark to leave him with Johnny, and they step back to give him a moment, but ultimately they all stay and comfort each other as the police arrive.", rating: 4)
on_the_line = Movie.create(genre_id: 3, title: "On the Line", description: "Kevin (Lance Bass) is performing with his band at a high school graduation party. When he sees an attractive girl, his bandmates try to get him to sing to her and ask her out. He becomes nervous, and envisions himself nude in front of everyone, and faints. Seven years later, Kevin is working in advertising. He makes a pitch for Reebok that is rejected, though the pitch is later used in the meeting by his 'partner' Jackie (Tamala Jones), who presents it as hers. As he takes the train home from work, Kevin meets Abbey (Emmanuelle Chriqui), with whom he finds he has much in common, such as their mutual interest in the Chicago Cubs and Al Green.

Kevin tries to find Abbey by making posters imploring Abbey to contact him, and placing them all over town. He goes out with a few random women who respond, none of whom are Abbey. The local newspaper finds out about his search and sets up an interview. The reporter, Brady Frances (Dan Montgomery, Jr.), is an old classmate who harbors ill will toward Kevin, on account of a girl in high school who rejected Brady for Kevin. When Brady's article is published, Kevin gets hundreds of calls, which leads to his dateless roommates — aspiring musician Rod (Joey Fatone); slacker Eric (GQ); and art aficionado Randy (James Bulliard) — suggesting they date all the callers to help. Kevin rejects this idea, but a miscommunication leads Eric to believe that Kevin has approved it. A follow up article is published in which Brady portrays Kevin as a failure, which garners even more calls from women. Brady is further irritated when his girlfriend Julie (Amanda Foreman), who is bothered by his grudge against Kevin, takes Kevin's side.

Meanwhile, Abbey is having problems with her boyfriend of three years, whom she was visiting when she met Kevin. Her boyfriend buys tickets to an Al Green concert, but then cancels at the last minute. Kevin is also at the concert, but they never see each other, despite several close calls. As Kevin's roommates date the women who responded to the articles in order to find Abbey, they encounter Julie. When she tells Brady that Kevin's friends are answering the calls and dating the respondents, Brady reports this as a scam in a follow-up article. As a result, Reebok declines to work with Kevin, and he is taken off the project. When Kevin subsequently sees Abbey waiting for a train, he tries to get her attention but she only sees him after she boards the train, and the doors close before he can get to her. Rod showed his date (Chyna) how he played guitar he accidentally kicked her causing her to have a broken nose and ankle, He told it to Eric and Randy and after they heard he kicked her by accident they laugh but he tells them that it wasn't funny. Meanwhile Kevin learns that Abbey responded to his public search for her, and when he learns that Eric went out on a date with her, he punches Eric.

After Kevin's best friend at the agency, Nathan (Jerry Stiller), suffers a heart attack, Kevin visits him at a rehab facility, where Nathan tells him the story of both meeting his wife at a Chicago Cubs game, and catching a home run from Cubs legend Ernie Banks the same day, and how the two events are tied together. He gives Kevin the baseball and tells him to try to find Abbey again.

Jackie apologizes to Kevin, and places him in charge of the campaign's billboards. He uses the billboards to publicly ask Abbey to meet him at the train station at a specific day and time, which garners the interest of the media, who wait with him at the scheduled time. Kevin and Abbey are reunited at the station, much to the delight of the crowd at the station, to the television viewers at home, and to his roommates watching this unfold in a bar. In addition, Randy meets a woman who enjoys art as he does, Julie dumps Brady for Rod, who is offered a recording contract by a record label after listening to a demo tape of his that Kevin sent them, and Brady is given an advice column in the Living section of the Chicago Times.", rating: 4)
bangkok_dangerous = Movie.create(genre_id: 4, title: "Bangkok Dangerous", description: "Joe (Cage) is a professional freelance contract killer who works strictly by the rules; never socializing outside his work, staying secluded in quiet spots, never interacting or meeting with his handlers and always leaving on time without a trace. He usually hires young pickpockets or small-time criminals as his local help, whom he usually murders after the end of the job to prevent any identification. He uses multiple aliases and also has middlemen between him and his handlers. He also carries a watch to perform a hit in specific time and correctly visualizes his every target.

After completing a hit in Prague and killing his current help, Joe travels to Bangkok for an assignment to assassinate four people for notorious Bangkok crime boss Surat, whom he never meets. Joe occasionally provides insight via voiceover narration throughout the film. He hires a local Thai pickpocket named Kong, who has simple English knowledge, as his go-between in Bangkok, a condition of the contract being that the gang will never meet Joe. Contracts from the Bangkok gangsters are passed to Kong one by one via a nightclub dancer, Aom. Joe's first execution in Bangkok is done on motorcycle; when the target car stops at a red light, Joe kills all the occupants with a machine pistol.

Kong retrieves information about the second target, again via Aom, and the pair become friendlier with every contact. Before Joe executes his mission, Kong informs him of the target, Pramod Juntasa, another notorious gang lord and Surat's rival crime boss who acts as a sex trafficker, buying young girls from impoverished parents and selling them after sex deals. Joe sneaks into the target's penthouse and drowns him in his pool. Unsatisfied with Kong's assistance, Joe contemplates killing him, but after a brief confrontation when Kong is ambushed by local gangsters regarding a briefcase containing information files of Surat's/Joe's targets, he instead decides to act as Kong's mentor and trains him for self-defense.

Midway through the movie, Joe meets Fon, a deaf-mute pharmacist, with whom he becomes intrigued after a brief consultation. Joe later returns to the pharmacy to invite Fon out for dinner. Soon after Joe falls for Fon and meets her mother. The affair is cut short when he shoots and kills two assailants in Fon's presence. Blood splatters on Fon, and she runs off, trembling and traumatized by the violent deaths. Feeling betrayed, Fon cannot forgive Joe and ends their relationship.

Before the third kill, the gang attempts to identify Joe, and he warns them off. For the third execution that takes place at the Damnoen Saduak floating market, Kong assists Joe. The kill does not go as planned, and the target, a playboy and a criminal underworld associate, nearly gets away but Joe manages to catch and assassinate him. Before beginning his last mission Joe visits Fon, presumably to say goodbye. She initially ignores him but as Joe begins to drive away she runs after his car.

His fourth target is the Prime Minister of Thailand, who is revered by many but a great hindrance to Surat due to his hard-line crackdown on organized crime. Joe is about to make the kill when he has second thoughts, is spotted, and escapes through a panicking crowd. Meanwhile, the gang has abducted Aom and Kong with plans to execute them. Joe, now a target, is attacked at his house by four of Surat's henchmen. He uses explosives to take them out and is faced with the choice of rescuing Kong or leaving the country unharmed. Joe decides to rescue Kong, so he sets off to the gang's headquarters with one of the half-alive attackers.

Joe goes to the gang's headquarters, kills most of the gang including Surat's underboss/bodyguard (who is blown into half by explosives), and saves Kong and Aom. The fearful gang leader flees to his car with three other accomplices. Joe spots him and shoots the gang members, then gets into the back seat with Surat. As the police arrive at the location, Joe realizes he has only one bullet. He puts his head adjacent to Surat's, puts the gun up to his temple and pulls the trigger, killing himself and Surat.

Alternate ending
An alternate ending to the theatrical version shows that before Joe kills himself in the original version, Kong steals a police car and comes to his rescue. He kills Surat and runs to the stolen car (although he is shot once in the arm). After eluding the police officers, they hide in a neighborhood a few meters away from Surat's headquarters. As locals come out to investigate the commotion, Kong reveals Joe is the man who killed Surat. They help him recuperate while one local remarks Surat's bad reputation, adding his death marks an end to his crimes and atrocities in their place. Kong then takes Joe to a boatman and gives him his passports, so he may flee the country. Joe thanks Kong for his assistance and gives him a bank account number with 'a bonus', stating he was a good student. Joe then departs, with the camera focused on Kong (from Joe's perspective, similar to the original ending).", rating: 5)
hot_tub_time_machine = Movie.create(genre_id: 5, title: "Hot Tub Time Machine 2", description: "Five years after the events of the first film, Lou Dorchen and Nick Webber have become rich and famous, with Lou becoming a multi-billionaire and Nick being a successful musician/singer. At Lou's celebratory party, Lou is shot in the groin. Jacob (Lou's son) and Nick drag him to the hot tub time machine and activate it to travel back in time to find and stop the killer. When they awaken they find themselves ten years in the future, where Jacob is in charge of Lou's mansion. After determining that they are in an alternate timeline where Lou's killer is from this future, they go to their friend Adam Yates's home, only to meet his son Adam Yates Stedmeyer (Adam Jr.) who is engaged to a girl named Jill.

Lou suspects his nemesis Gary Winkle is the killer, but he learns Gary actually made his own fortune from some land that Lou could have purchased. They party at Gary's nightclub, where Adam Jr. takes hallucinogens for the first time. The next day, they attend the popular television game show Choozy Doozy, where contestant Nick is required to have virtual reality sex with a man. As Lou suggested the idea, he is obliged to participate, but uses his 'lifeline' to switch with Adam Jr. Jacob becomes disillusioned with the misadventures and leaves the group to get drunk at Gary's club and to then commit suicide by jumping off an extremely high building. Lou makes amends with him and prevents his suicide.

When the guys see a news report where Brad, an employee of Lougle, invents nitrotrinadium, the ingredient that activates the hot tub time machine, they suspect he is the killer. At Adam Jr's wedding, Jacob talks with Brad and realizes he is not the killer but that he invented the chemical after being inspired by Lou's words. Jill, who is upset about Adam Jr's partying, has sex with Lou, but when Adam Jr. finds out, he steals the nitrotrinadium and goes back to the past. Jacob, Nick and Lou return to the mansion, but are too late to stop Adam Jr. As the guys sit in defeat, Jacob realizes that because the chemical has appeared in the past, it now exists in the future. They return to the present and stop Adam Jr. from shooting Lou after Lou apologizes to him.

Following this incident, Nick apologizes to Courtney as Lou tells his wife he wants to go to rehab for his drug addictions. Adam Jr. meets Jill for the first time. The more optimistic Jacob approaches Sophie (his girlfriend in the future) and convinces her to join him in a relationship. As Lou, Nick, Jacob, and Adam Jr. return to the hot tub, Lou's head is shot off by a Lou (or Adam Sr. in the Unrated version) dressed in a minuteman costume. Patriot Lou informs them there are multiple Lous anyway and invites them to 'make America happen.' During the closing credits, the guys are seen exploiting the time machine to change history.", rating: 5)
gigli = Movie.create(genre_id: 6, title: "Gigli", description: "Larry Gigli is a low-ranking Los Angeles mobster who is not nearly as tough as he likes to act. Louis, a higher-ranking member of Gigli's organization, commands Gigli to kidnap the mentally challenged younger brother of a powerful federal prosecutor to use as a bargaining chip to save New York-based mob boss Starkman from prison. Gigli successfully convinces the young man, Brian, to go off with him by promising to take him 'to the Baywatch', apparently a reference to the television show of that name, which seems to be Brian's singular obsession. Louis does not trust Gigli to get the job done right, so he hires a woman calling herself Ricki to take charge.

Gigli is attracted to Ricki, but he resents both Louis' lack of faith in him and having to take orders from a woman. He is also frustrated by Brian's insistence on going to 'the Baywatch' and by the fact that Ricki is a lesbian. A suspicious detective comes to the apartment to question Gigli in reference to Brian's disappearance. Gigli is further annoyed when his mother takes an immediate liking to Ricki and when the two women team up to needle him.

The events take a darker turn when Gigli and Ricki receive orders to cut off Brian's thumb, something that neither wants to do. Worse, Ricki's ex-girlfriend, Robin, shows up at Gigli's apartment, accusing Ricki of changing sexual orientation. She attempts suicide by slitting her wrists and is rushed to the hospital, where she thankfully survives. While there, Gigli sneaks into the morgue and cuts off a corpse's thumb, which he sends to the prosecutor as Brian's thumb. Gigli and Ricki go back to Gigli's apartment, where Gigli confesses his love and the two sleep together.

They are summoned to meet with the mob's boss. Starkman reveals that he did not approve of the plan to kidnap a federal prosecutor's brother or the order to cut off Brian's thumb. He nevertheless rages at them because the thumb they sent didn't match Brian's fingerprint, and therefore not only failed to increase pressure on the prosecutor but even undermined the organization's credibility.

Starkman then kills Louis, presumably in retaliation for the kidnapping and associated scrutiny by law enforcement. Starkman is about to kill Ricki and Gigli as well, but Ricki talks him out of it by pointing out that only they know where Brian is and only they can silence Brian and prevent him from revealing the involvement of Starkman's organization in the kidnapping or even accusing Starkman of having been personally involved.

They leave Starkman's, decide to leave the mob, and discuss taking Brian back to where they found him. On the way, they discover Baywatch (or a similarly themed show or film) shooting an episode on the beach. Brian begs to be let off there and finally they consent. Gigli convinces Ricki to take his car to escape to parts unknown; but at the last minute, Ricki returns to pick up Gigli, and they leave town together.", rating: 2)
the_king = Movie.create(genre_id: 7, title: "In the Name of the King: A Dungeon Siege Tale", description: "In the kingdom of Ehb, a man known only as Farmer is living a happy life with his wife, Solana and their young son, Zeph in the town of Stonebridge. One day, the town gets attacked by creatures known as the Krug. The Krug, who are known to be primitive and animal-like, surprise the people by taking up arms, donning armor and are fighting with courage, intelligence and ferocity. It's all because of they're magically controlled by Gallian, a powerful Magus who has become sadistic and megalomaniacal, and seeks to conquer and rule Ehb. During the attack, Farmer, along with his friend, Norick and his brother-in-law, Bastian, fights off the Krug, but fails to save Zeph; who gets killed by Gallian via a Krug avatar. Solana and other Stonebridge inhabitants are taken prisoner.

King Konreid, commander Tarish and a company of Ehb's army arrives at Stonebridge to survey the damage and recruit others to join their army. Merick, another Magus who serves Konreid, tries to learn of Farmer's identity when he notices Norick, who he believes he has seen before. Farmer, Norick and Bastian set off on their own to find Solana. Meanwhile, Merick's daughter, Muriella, who fell in love with Gallian, ends her romance with him after seeing his dark nature and realizing that he only trained her power so he can take it away. She confesses to her father, who believes that her love for Gallian has created an imbalance of their powers in Gallian's favor. Meanwhile, Konreid's selfish and immature nephew, duke Fallow is in league with Gallian and he seeks to take his uncle's place. He attempts to poison Konreid and takes a company of Ehb soldiers for his own. Soon after, Konreid heals and leads his army to go and fight Gallian's forces.

Going through Sedgwick Forest, Farmer and his companions encounter the reclusive nymphs led by Elora, who leads them out of the forest. When they attempt to rescue Solana from the Krug, Farmer gets knocked out, and Norick and Bastian get captured. When Farmer is getting hanged by another one of Gallian's avatars, he kills the avatar, frees himself and is rescued by Merick. Farmer is taken to Konreid and his army's camp, where Merick reveals that Farmer is Konreid's long lost son and his real name is Camden Konreid. He explains that many years ago, a young Farmer was present during a battle at a place known as Oxley Pass, where he was found by Norick. Norick was considered to be the adoptive father, but Farmer was cared for by Stonebridge's inhabitants and was kept safe from all the chaos that ravaged Ehb. Konreid and Farmer both disapprove of Merick's claims.

Konreid catches Fallow, in his treachery, which leaves Fallow only his personal guard as the company turns from him and joins the rest of the army. Soon after, a battle erupts between Ehb's army and the Krug. Ehb's army, along with Farmer, eventually gain the upper hand and force the Krug to retreat, but Fallow succeeds in mortally wounding Konreid. After the battle, Konreid and Farmer learn that they both share similar knowledge as Konreid declares Farmer his son with his dying breath and dies. Meanwhile, Tarish challenges Fallow to a duel. Tarish wins and Fallow gets taken away. Farmer, who is now the new king, gets everybody ready for the next battle.

Meanwhile, Norick, Bastian and Solana are taken to Gallian's lair at Christwind Hold. Norick gets killed while trying to fight back and Solana gets taken to Gallian, whose sense of royal blood reveals that Solana is pregnant with Farmer's second child. Going on a mission to infiltrate Gallian's lair, Farmer is joined by Merick, Muriella and Elora, who has sided with Ehb against Gallian, while Tarish and the remaining army hold off against the advancing Krug. Merick magically enters the lair and fights Gallian, who manages to kill Merick. Farmer and Muriella manage to get into the lair as well, but Elora stays behind.

Farmer finds Solana and fights Gallian in a sword battle. When Gallian resorts to using his magic to gain the upper hand, he prepares to kill him until Solana stabs him in the back. Muriella arrives and tries to save Farmer but Gallian defeats Muriella by weakening her magic. With him wounded, Farmer quickly defeats Gallian by slitting his throat and killing him. Gallian's magic influence goes away and the Krug go back to being primitive, saving Bastian and the prisoners, and Tarish and his battered forces. Having finally avenged his son, Farmer and Solana are happily reunited as the kingdom is saved.", rating: 4)
mummy = Movie.create(genre_id: 8, title: "The Mummy: Tomb of the Dragon Emperor", description: "In ancient China, a brutal and tyrannical warlord unites the country's kingdoms into an empire and becomes the Dragon Emperor. He orders the construction of the Great Wall of China to bury and curse his dead enemies, eventually learning power over the traditional Chinese Wu Xing elements of fire, water, earth, wood and metal. The Emperor soon grows fearful that his death will end all he has accomplished and summons Zi Yuan, a sorceress who is said to know the secret of immortality. He sends her with General Ming, his trusted friend to an ancient monastery. There, Ming and Yuan find a spellbook known as the Oracle Bones where love blossoms between them while the Emperor also lusts for the latter. There, the two sleep together without dress and have sex. Having witnessed this, the Emperor kills Ming after having Yuan perform the procedures and then stabs her with a dagger, but having foreseen this event, she immolates and imprisons the Emperor and his soldiers in clay, turning them into the Terracotta Army, and flees.

In 1946, Alex O'Connell, Rick and Evelyn O'Connell's son, and his archaeology professor Roger Wilson locate the emperor's tomb. Though attacked by a mysterious woman, they succeed in bringing the sarcophagus to Shanghai. Meanwhile, the British government entrusts the O'Connells to take the Eye of Shangri-La gemstone back to China. However, they learn that Wilson works for a rogue military faction led by General Yang, who had provided the financial backing of Alex's expedition. Yang believes that the Emperor is the one who can lead China out of the chaos following World War II and plans to resurrect him using the Eye, which contains the Elixir of Life. They open it, but it accidentally lands on the statue of the carriage driver, which is soon revealed to be the Emperor's mummified body. He accepts Yang's service but kills Wilson and escapes, despite the O'Connells' attempt to stop him in a pursuit.

Along with Evelyn's brother Jonathan Carnahan, the O'Connells and the mysterious woman, Lin, travel to a stupa in the Himalayas that will reveal the path to Shangri-La when the Eye is placed on top of it. With the help of Yetis summoned by Lin, the group hold off Yang's soldiers but the Emperor discovers Shangri-La's location. Alex attempts to trigger an avalanche. The Emperor throws a sword at him, but Rick shoves Alex aside and is stabbed instead. Lin takes the group to Shangri-La, where Zi Yuan still lives and heals Rick's wound. The group discovers that Lin is Zi Yuan's daughter, both rendered immortal due to the power of Shangri-La's waters. As Rick heals, Alex and Lin have grown attached to each other, but Lin refuses due to her immortality, unable to bear falling in love with Alex only to watch him grow old and die, just as Zi Yuan mourned for General Ming.

The Emperor and General Yang eventually arrive and attack them in Shangri-La and the Emperor bathes in the mystical waters, which not only restores his human form and youth, but also allows him to shapeshift. Transforming into a three-headed dragon, he kidnaps Lin and flies back to the tomb, raising his Terracota Army, and gives a speech declaring his intention to conquer the world before sending his soldiers to go past the Great Wall, after which they will be invincible. The O'Connells and Zi Yuan pursue their foe to the Great Wall where Zi Yuan sacrifices her and Lin's immortality to create an undead army from beneath The Great Wall, led by a revived General Ming. As Alex rescues Lin, Zi Yuan fights the Emperor and is mortally wounded, but secures the dagger. Zi Yuan gives the dagger to the group before dying. Meanwhile, the Emperor goes into the Great Wall to use his elemental powers to negate the undead spell. Rick and Alex attack him while Evelyn and Lin fight and kill Yang and Choi. The Emperor gains the upper hand over Rick, but Rick and Alex manage to stab him in his heart with the broken dagger, killing him and defeating the Terracotta Army. Ming's army briefly celebrates before turning into dust and disappearing into the air to rest in peace.

The O'Connells and Lin return to Shanghai, where Lin and Alex start a relationship, while Jonathan decides to move to Peru with the Eye of Shangri-La, as he wants to go somewhere with no mummies, only for credits on the screen to reveal that mummies were recently discovered there.", rating: 5)
fan = Movie.create(genre_id: 9, title: "The Fan", description: "Gil Renard is a troubled baseball fan whose favorite team, the San Francisco Giants, have just signed a $40 million contract with his favorite player, Bobby Rayburn. His ex-wife Ellen obtains a restraining order to keep him away from herself and their son after Gil left his son to attend a sales meeting, but finds his client is at a baseball game. Gil is fired from his job as a knife salesman when he threatens a prospective customer.

Gil begins harboring an obsession with Rayburn. When Rayburn suffers a chest injury that causes fans to be upset by his under performance, Gil shows aggression to fans that jeer him. Rayburn has also been in an open conflict with teammate Juan Primo due to both men using jersey number 11, and neither wanting to give it up, due to their long histories and connections to the number. Rayburn was instead given number 33, and harshly protested it. This culminates in a fight in the restroom of a bar. So Gil, thinking that Primo is to blame for Rayburn's performance, confronts him in a hotel sauna in an attempt to persuade him to let Rayburn have the number. Primo reveals his shoulder, branded with the number 11, and says that it is his number. This eventually leads to a struggle, and Gil stabs Primo to death. Although Rayburn is suspected of the murder, his performance improves, and Gil believes that what he did was good for Rayburn and the team. After feeling guilty about Primo's death, Rayburn starts playing well again.

Thinking that Rayburn does not acknowledge his fans, Gil goes to Rayburn's beach house and saves his son Sean from drowning. Gil persuades Rayburn to play a friendly game of catch on the beach. Rayburn says he stopped caring about the game after Primo's death, because he felt there were more important things in life. He makes the mistake of telling Gil that he has lost respect for the fans, remarking on their fickle nature — when he's hitting, they love him, but when he's not, they hate him. An angered Gil almost hits Rayburn with a fastball and launches into a diatribe. Rayburn is disturbed, especially when Gil takes off his jacket to reveal Rayburn's uniform underneath and wonders if Rayburn is happy that Primo's not around.

Rayburn soon discovers that Gil has kidnapped Sean and left piece of Primo's branded shoulder in the freezer. Disillusioned with Rayburn's disrespect towards the fans, Gil spirals further into insanity and acts as though Sean is his own son. He drives to see an old friend, Coop, a catcher that Gil spoke often of playing baseball with in his past. Coop tries to help Sean escape, and reveals that the only time he and Gil ever played together was in the Little League. Gil then beats Coop to death with a baseball bat and takes Sean to a baseball field, hiding him there.

Gil contacts Rayburn to make one demand: hit a home run in the upcoming game and dedicate it to Gil, or he will kill his son. With the police on high alert, Gil enters Candlestick Park in the midst of an on-and-off thunderstorm. Rayburn struggles with his emotions while at bat. After several pitches, he finally hits the ball deep into the outfield but not over the fence. Rayburn attempts to score an inside-the-park home run. He is called out, even though he is obviously safe. Rayburn argues with the umpire, who turns out to be Gil in disguise.

Rayburn knocks Gil to the ground. Dozens of cops and Giants players swarm onto the field and confront Gil. Before the cops arrive, Gil kills another player, Lanz, who tries to tackle him. Despite warnings from the police, Gil goes into an exaggerated pitching motion with a knife in hand. He asks Rayburn if he cares about baseball, then assumes that he cares 'just a little bit.' Gil is shot dead as he is about to throw the knife. Police discover Sean at the Little League field, where Gil once played in his childhood. They uncover his obsession with Rayburn, as hundreds of newspaper clippings adorn the deranged fan's hideout. A picture on the wall shows Gil in his past glory, playing Little League baseball and winning a game.", rating: 6) 
d_n_d = Movie.create(genre_id: 10, title: "Dungeons and Dragons", description: "The Empire of Izmir has long been a divided land, ruled by the Mages, an elite group of powerful warlocks. In the capital of Sumdall, one individual, an evil mage named Profion, creates a magical sceptre that can allow him to control Gold dragons, but his attempt to control an individual fails, and he is forced to kill it. As he begins to make new plans, the dragon bleeds into the nearby river, causing it to catch fire, which many inhabitants notice, including a pair of teenage thieves, Ridley and his best friend Snails.

Later, Profion and the Council of Mages discuss the controversial views of Empress Savina, who wants to give rights to non-mages in Izmir. When the Council threatens to confiscate from her the scepter that allows her to control Gold dragons, she decides to seek the Rod of Savrille, which controls Red dragons. Profion learns of this and decides to take the Rod himself. Meanwhile, Ridley and Snails break into the Sumdall magic school to steal valuables and other items to become rich, but are discovered by a young Mage named Marina. She is distracted when the library wizard is held hostage and interrogated by Profion's assistant Damodar for information on the map to the Rod. After the wizard refuses to talk and sends the map over to Marina, Damodar kills him, and Marina travels through a portal to escape, taking the thieves with her. After crashing into a pile of garbage, they meet a dwarf named Elwood, who ends up joining the three's escape through the sewers.

Damodar puts a price on Marina, Ridley, Snails and Elwood's heads and after letting Profion know that the group got away with the map, Profion creates a tentacled monster inside Damodar which possesses him. The group hide inside a tavern and read the map that Ridley and Marina get sucked into. Damodar and his minions attack Elwood and Snails, but they escape with the map. Ridley and Marina exit the map and all decide to work together to find the Rod. They must first find a ruby called the 'Eye of the Dragon' that can open the door to a tomb containing the sceptre. The Eye is held by the thieves' guild in the city of Antius, whose leader, Xilus, promises to give the group the 'Eye of the Dragon' if Ridley solves a maze puzzle of traps. Ridley successfully passes through every trap and retrieves the 'Eye of the Dragon' when Damodar suddenly arrives to capture him and his friends. Marina is captured instead while Ridley, Snails and Elwood escape, meeting an elf named Norda who works for Empress Savina, whom she informs about Profion's plan to obtain the Rod. In his castle, Damodar interrogates Marina and uses the tentacles in his mind to gain her knowledge.

Ridley and Snails break into Damodar's castle to rescue Marina, while Norda and Elwood stay behind. After Ridley and Snails decide to split up, Ridley finds and rescues Marina, but Snails is confronted by Damodar after he finds the map and a fight ensues between the two with Damodar gaining the upper hand. When Ridley and Marina arrive, Snails throws the map to his comrades, but at the cost of his own life as he is killed by Damodar before being thrown off the castle. Ridley, infuriated and filled with rage, attacks Damodar to avenge his friend, but he disarms him and stabs Ridley with his own sword. In the confusion, Marina grabs some magic dust and creates a magic portal to escape with Ridley. Meanwhile, during a Council meeting, Profion and Savina's factions decide to battle for control of Izmir using magic.

At the same time, an elf heals Ridley along with Norda's soldiers. Later, Marina finds Ridley and tries to help him get over the death of Snails, but Ridley, still feeling remorseful of his friend's death, angrily scolds her for letting Snails die instead of saving him. After a brief argument between the two in which Marina convinces Ridley that Snails' death was not in vain, they eventually forgive each other and become love interests. Ridley later uses the 'Eye of the Dragon' to enter the tomb that contains the Rod. It is held by a skeleton that comes to life and tells Ridley he is Savrille, now cursed for trying to control red dragons, and 'Anyone who wields the power of the Rod shall suffer a horrible fate', but Damodar arrives to steal the Rod.

Damodar returns to Sumdall with the Rod, where the Empress and her Gold dragons are battling the Mages following Profion below, to bring it to Profion, but Ridley and his friends follow in pursuit. Profion removes the monster from Damodar and uses the Rod to summon Red dragons, which battle the Gold dragons and slowly begin to win the fight. Ridley comes across Damodar, duels him with his new magic sword and then successfully wounds the latter before finishing him off by hurling Damodar off the castle wall to his death, finally avenging Snails. He then attacks Profion, who disarms him and shoves him back. Ridley's companions arrive and fight Profion one at a time. Ridley picks up the fallen Rod, and uses it to stop the red dragons. Marina encourages Ridley to use the Rod to bring Profion down, but Ridley, realizing the Rod's power will corrupt him, refuses and destroys it. Empress Savina arrives and condemns Profion, who fights her with powerful magic, but she summons a Gold dragon which devours Profion, ending the battle and Profion's reign of terror.

Ridley later visits Snails' grave with Norda, Marina and Elwood and pays tribute to his fallen comrade. When he places the 'Eye of the Dragon' on the grave, Snails' name disappears, and Norda tells Ridley not to question his abilities. Norda then uses the 'Eye of the Dragon' to transport Ridley to another place in the world where his friend would await for him, along with herself, Marina and Elwood.", rating: 4)
jonah_hex = Movie.create(genre_id: 11, title: "Jonah Hex", description: "During the American Civil War, Jonah Hex (Josh Brolin) serves as a Confederate cavalryman until his commanding officer Quentin Turnbull (John Malkovich) orders him to burn down a hospital. Hex refuses, and is forced to kill his best friend, Turnbull's son Jeb. After the war, Turnbull and his enforcer Burke (Michael Fassbender) force Hex to watch his house burn down with his wife and son inside. Turnbull brands Hex's face with his initials and leaves him to die. Native Americans revive Jonah with mystic powers, giving him the ability to temporarily resurrect the dead. When Turnbull apparently dies in a hotel fire, Hex satisfies his hunger for vengeance as a bounty hunter and sears half his face to remove the brand.

In 1876, Turnbull, having survived, hijacks a train carrying components of an experimental 'superweapon,' slaughtering guards and passengers. President Grant (Aidan Quinn) surmises that Turnbull is planning a terrorist attack for the American Centennial on the Fourth of July, and instructs Army Lieutenant Grass (Will Arnett) to hire Hex to stop Turnbull.

Hex spends a night with Lilah (Megan Fox), a prostitute with ulterior motives. Grass's men arrive and reveal Turnbull is still alive. Hex is brought to one of Turnbull’s captured thugs, who dies during interrogation. Hex briefly resurrects the man, who knows only that he was recruited by ex-Confederate Colonel Slocum (Tom Wopat), the owner of an illegal deathmatch pavilion in South Carolina.

With the help of corrupt Washington aristocrat Adleman Lusk (Wes Bentley), Turnbull steals the remaining components of the weapon invented by Eli Whitney.

When Hex confronts Slocum in South Carolina, Slocum refuses to talk, sarcastically telling Hex to ask Jeb where his father is. Hex overpowers Slocum's men and throws him into the ring to be killed by his own fighters. Setting fire to the pavilion, Hex frees a dog tormented by Slocum's handlers, and it follows him.

In a Gettysburg cemetery, Hex digs up and resurrects Jeb (an uncredited Jeffrey Dean Morgan). He apologizes for killing Jeb, telling him his father must be stopped before he murders more people. Before returning to the afterlife, Jeb reveals his father is at Fort Resurrection.

At the fort, Hex confronts Turnbull and kills several of his men, but Turnbull escapes and Hex is critically wounded by Burke. He collapses in a field, hovering near death for several days. Turnbull, anticipating Hex's return, sends Burke to bring him 'something Hex loves,' and Burke kidnaps Lilah. Turnbull tests the 'superweapon' on a small town in Georgia, leveling it to the ground and killing hundreds. Grant realizes authorities have neither any idea where Turnbull will strike, nor the military manpower to guard every centennial celebration.

Hex’s Native American allies find him and perform a ceremony that heals him. He relays a message to Lt. Grass that Turnbull plans to attack Washington, D.C., then rides to Independence Harbor alone to stop him. Hex infiltrates the harbor where Turnbull's ironclad warship is anchored, overpowering and killing Burke, then resurrects him just to incinerate his body completely. Turnbull holds Lilah at gunpoint and forces Hex to surrender. With Hex and Lilah captive in the hold of his ship, Turnbull steams toward Washington. A monitor commanded by Lt. Grass intercepts Turnbull, but is quickly destroyed by the superweapon.

Lilah frees herself and Hex, holding off the guards while he races to stop Turnbull. Turnbull gains the upper hand and orders the weapon be fired, but Hex jams its belt feeder, trapping the trigger shell. He brutally beats Turnbull and traps his neck in a gear and then saves Lilah. They jump into the water just as the trigger shell ignites, killing Turnbull and his men. The next day, President Grant gives Hex a large reward and a full pardon, and offers him a job as Sheriff of the entire United States. Hex declines, but assures the president they can find him if they need him; he leaves the city with Lilah. The film ends with Hex visiting Jeb's grave to apologize for his father’s death before riding off.
", rating: 5)